# Generated by Django 6.0.3 on 2026-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('angry', '😡 Angry')], default='neutral', max_length=10),
        ),
    ]
